/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/src/drawer`; params?: Router.UnknownInputParams; } | { pathname: `/src/FilesTab`; params?: Router.UnknownInputParams; } | { pathname: `/src/main`; params?: Router.UnknownInputParams; } | { pathname: `/src/PhotosTab`; params?: Router.UnknownInputParams; } | { pathname: `/src/Authscreen/authscreenhandler`; params?: Router.UnknownInputParams; } | { pathname: `/src/createAccount/manualsignup`; params?: Router.UnknownInputParams; } | { pathname: `/src/GlobalVariables/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/src/googlesignin/googlesignin`; params?: Router.UnknownInputParams; } | { pathname: `/src/otpscreen/otp`; params?: Router.UnknownInputParams; } | { pathname: `/src/PhotoSubTab/AlbumView`; params?: Router.UnknownInputParams; } | { pathname: `/src/PhotoSubTab/FavouritesView`; params?: Router.UnknownInputParams; } | { pathname: `/src/PhotoSubTab/GalleryView`; params?: Router.UnknownInputParams; } | { pathname: `/src/PhotoSubTab/RecentView`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/src/drawer`; params?: Router.UnknownOutputParams; } | { pathname: `/src/FilesTab`; params?: Router.UnknownOutputParams; } | { pathname: `/src/main`; params?: Router.UnknownOutputParams; } | { pathname: `/src/PhotosTab`; params?: Router.UnknownOutputParams; } | { pathname: `/src/Authscreen/authscreenhandler`; params?: Router.UnknownOutputParams; } | { pathname: `/src/createAccount/manualsignup`; params?: Router.UnknownOutputParams; } | { pathname: `/src/GlobalVariables/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/src/googlesignin/googlesignin`; params?: Router.UnknownOutputParams; } | { pathname: `/src/otpscreen/otp`; params?: Router.UnknownOutputParams; } | { pathname: `/src/PhotoSubTab/AlbumView`; params?: Router.UnknownOutputParams; } | { pathname: `/src/PhotoSubTab/FavouritesView`; params?: Router.UnknownOutputParams; } | { pathname: `/src/PhotoSubTab/GalleryView`; params?: Router.UnknownOutputParams; } | { pathname: `/src/PhotoSubTab/RecentView`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/firebaseConfig${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/src/drawer${`?${string}` | `#${string}` | ''}` | `/src/FilesTab${`?${string}` | `#${string}` | ''}` | `/src/main${`?${string}` | `#${string}` | ''}` | `/src/PhotosTab${`?${string}` | `#${string}` | ''}` | `/src/Authscreen/authscreenhandler${`?${string}` | `#${string}` | ''}` | `/src/createAccount/manualsignup${`?${string}` | `#${string}` | ''}` | `/src/GlobalVariables/AuthContext${`?${string}` | `#${string}` | ''}` | `/src/googlesignin/googlesignin${`?${string}` | `#${string}` | ''}` | `/src/otpscreen/otp${`?${string}` | `#${string}` | ''}` | `/src/PhotoSubTab/AlbumView${`?${string}` | `#${string}` | ''}` | `/src/PhotoSubTab/FavouritesView${`?${string}` | `#${string}` | ''}` | `/src/PhotoSubTab/GalleryView${`?${string}` | `#${string}` | ''}` | `/src/PhotoSubTab/RecentView${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/src/drawer`; params?: Router.UnknownInputParams; } | { pathname: `/src/FilesTab`; params?: Router.UnknownInputParams; } | { pathname: `/src/main`; params?: Router.UnknownInputParams; } | { pathname: `/src/PhotosTab`; params?: Router.UnknownInputParams; } | { pathname: `/src/Authscreen/authscreenhandler`; params?: Router.UnknownInputParams; } | { pathname: `/src/createAccount/manualsignup`; params?: Router.UnknownInputParams; } | { pathname: `/src/GlobalVariables/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/src/googlesignin/googlesignin`; params?: Router.UnknownInputParams; } | { pathname: `/src/otpscreen/otp`; params?: Router.UnknownInputParams; } | { pathname: `/src/PhotoSubTab/AlbumView`; params?: Router.UnknownInputParams; } | { pathname: `/src/PhotoSubTab/FavouritesView`; params?: Router.UnknownInputParams; } | { pathname: `/src/PhotoSubTab/GalleryView`; params?: Router.UnknownInputParams; } | { pathname: `/src/PhotoSubTab/RecentView`; params?: Router.UnknownInputParams; };
    }
  }
}
